export { MaxWidthWrapper } from './MaxWidthWrapper'
export { Phone } from './Phone'
export { Navbar } from './Navbar'
export { Icons } from './Icons'
export { Reviews } from './Reviews'
export { Footer } from './Footer'
export { Steps } from './Steps'
